### ISSUE TITLE
Sobre esse repositório

### ISSUE THREAD

**Issue by sibelius** [react-native-dojo/react-native-dojo#1]
Esse repositório surgiu com uma ideia maluca de criar um Dojo remoto para aprender e fazer varias amizades.

Vamos utilizar essa issue para ideias e possiveis apps que gostaríamos de desenvolver.

A ideia é que desenvolvermos tanto a parte do servidor (nodejs), da web (react) e do mobile (react native)
# Como funcionaria
- Primeiro definimos o app que iremos desenvolver
- Criamos as primeiras issues que temos que resolver para avançar o desenvolvimento do app, e lançar a fase alpha dele
- Depois das primeiras issues criadas, serão escolhidos/sorteados 3 devs (1 para o servidor, 1 para a web, 1 para o react native, talvez 6 para que trabalhem 2 em cada issue) para tentar resolver 3 issues no periodo de 2 dias, e enviando um PR para esse repositorio (não importa se não conseguirem terminar a issue inteira, isso indica que não dividimos em pedaços pequenos suficientes para serem desenvolvidos em 2 dias)
- 3 outros Dev são responsáveis de revisar as PRs enviadas
- E assim o ciclo continua

Podemos criar um slack ou gitter para que um possa ajudar ao outro

Obs.: isso não está fechado e definido, tudo pode mudar

Criem uma issue com a sua ideia (comentem +1 para votar na ideia), comentem aqui com o usuário do github se quiserem participar desse Dojo online para que possamos saber quem está interessado

**Comment by sibeliusseraphini** [comment]
@rturk

# Ideia
Aplicativo para doação de sangue
- Mostrar Hospitais e pontos de coleta locais
- Push notification quando estoque de sangue estiver baixo
- Share em redes sociais
- Find friends
- Server side statistics


Podemos nos basear nesse app para a [NBA](https://github.com/wwayne/react-native-nba-app)

**Comment by sibeliusseraphini** [comment]
@sibeliusseraphini

# Ideia
Aplicativo para as Olimpíadas 2016 do Brasil
- Mostrar Atletas por pais e suas habilidades
- Mostrar Histórico de Medalhas
- Mostar horário dos eventos
- Entre outras coisas

Podemos nos basear nesse app para a [NBA](https://github.com/wwayne/react-native-nba-app)

**Comment by henriquesosa** [comment]
@sibeliusseraphini dividi as ideias em issues, assim acho que ficará mais facil de discutir cada uma. E, podemos tornar esse topico uma discussão geral. O que acha?

**Comment by sibeliusseraphini** [comment]
otimo

**Comment by maugravena** [comment]
Quero participar, existe alguma restrição?

**Comment by sibelius** [comment]
@maugravena sem restrições, só comentar com o seu usuário github, depois que definirmos o projeto vamos designar issues para os participantes.

Pode criar uma nova issue com a sua ideia de projeto, ou votar com :+1: em uma ideia já existente

**Comment by maugravena** [comment]
Meu usuário github: maugravena

**Comment by lucasbento** [comment]
lucasbsilva :)

**Comment by guipsamora** [comment]
guipsamora

**Comment by charbelrami** [comment]
charbelrami

**Comment by EduardoCHenrique** [comment]
eduardochenrique

**Comment by dehbmarques** [comment]
@dehbmarques

**Comment by gustvao** [comment]
@gustvao

**Comment by pedpess** [comment]
Muito interessante a ideia @sibeliusseraphini, quero participar!

**Comment by sibelius** [comment]
Vamos começar depois do carnaval - 10/02/2016.
Portanto, peço que votem e ou postem novas ideias até lá

**Comment by tzdesing** [comment]
muito legal , minha idéia é um app de video-depoimentos, exemplo :  semana q vem é aniversário do João , eu quero homenagea-lo , daí crio um evento e convido nossos amogos em comum, cada convidado recebe uma notificaçao (convite), através de redes sociais, ao clicar, o convidado pode pode gravar um video desejando felicidades ao João, ou contando o quanto ficaram bebados "naquela festa" , etc ,o objetivo é demonstrar  o qto o João é importante pra todos nós,  o sistema vai "juntar" os videos, e João receberá esse video quando chegar a data marcada, daí existem vários desdobramentos possíveis, video respossta, compartilhamento, top10 da semana, rede-social de homenagens, etc, parecido com o "Arquivo confidencial do Faustão" só q para não famosos...

ah , meu usuário >> @tzdesing

**Comment by charbelrami** [comment]
legal a ideia @tzdesing

**Comment by arthur-vieira** [comment]
@arthur-vieira

**Comment by bruno-fs** [comment]
existe um pré-requisito? tenho algum tempo de experiência programando, mas praticamente só em python e shell. estou começando o FCC AGORA

**Comment by sibelius** [comment]
@varnion sem nenhum pré-requisito

**Comment by ylaguna** [comment]
@ylaguna

**Comment by bruno-fs** [comment]
@sibeliusseraphini, ookie dookie. count me in, then.
@varnion

**Comment by sibelius** [comment]
Dojo começou - https://github.com/react-native-dojo/BloodDonationDojo/issues/1

**Comment by tzdesing** [comment]
?

**Comment by nicholasess** [comment]
@nicholasess
