### ISSUE TITLE
Aplicativo para Politica

### ISSUE THREAD

**Issue by sibelius** [react-native-dojo/react-native-dojo#11]
Hoje temos alguns sites que buscam criar um consciência maior sobre o cenário político do Brasil, tais como:

http://houseofcunha.com.br/# - 
http://qmrepresenta.com.br/

Temos o também esse aplicativo - http://congressoemfoco.uol.com.br/opiniao/colunistas/ops-lanca-aplicativo-para-fiscalizar-gastos-de-deputados-com-verba-indenizatoria/

https://itunes.apple.com/br/app/ops-fiscalize/id1016302793?l=en&mt=8

Temos acesso a diversos gastos pelo http://www.portaldatransparencia.gov.br/

**Comment by sibelius** [comment]
@RodolfoViana

**Comment by danilo-favoratti** [comment]
Olá, pessoal! Sou o desenvolvedor do Ops Fiscalize!

Temos uma série de softwares sendo desenvolvidos a fim de encontrar indícios de corrupção na política brasileira. Tenho conversado com o Sibelius e faremos uma reunião dia 17/02, 21h (a confirmar) para eu apresentar nosso projeto.

Quem quiser participar do bate-papo basta me avisar aqui: favoratti@gmail.com

Abraço!
