### ISSUE TITLE
Inflacionômetro

### ISSUE THREAD

**Issue by mfpalladino** [react-native-dojo/react-native-dojo#12]
## O que é?

A economia do Brasil dá sinais claros que vamos ter que voltar a nos acostumar com a inflação e com o aumento de preços. Este aplicativo é uma proposta para criação de um índice de inflação real e montado colaborativamente.
## Funcionalidades básicas

**Visualizações:** 
- Mapa do Brasil mostrando os índices por estado
- Número de usuários que realizaram marcações no mês/item avaliado
- Inflação comparada com o mês anterior
- Índices "espirituosos/críticos" para compartilhamento em redes sociais  

**Entrada de dados:** Inicialmente o aplicativo poderia focar na cesta básica (item). O usuário seleciona o item e o software, com base na média de preços do estado do usuário, apresenta uma lista como esta, por exemplo:

ARROZ (5KG)
- 7,50
- 8,00
- 8,50
- 9,00 (preço médio no estado)
- 9,50
- 10,00
- 10,50

**Comment by sibelius** [comment]
Podemos também pedir para que escaneem os recibos dos supermercados ou de outros itens para medirmos a inflação de forma mais automática, utilizando OCR.

Também podemos extrair essas informações da Nota Fiscal Paulista, se a pessoa pediu a nota com CPF

**Comment by sibelius** [comment]
+1
