### ISSUE TITLE
Guia de estudo para iniciantes

### ISSUE THREAD

**Issue by pedpess** [react-native-dojo/react-native-dojo#14]
Olá pessoal,

Não seria interessante a criação de um "caminho das pedras" de estudo também visando as boas práticas para o desenvolvimento do react desde o começo? No meu caso, eu sou iniciando no assunto e não entendo muito ainda. Acho que seria bastante válido. Ex: Livros, blogs, vídeos, como estudar usando o Git etc...

Oq vcs acham?

Vlw!

**Comment by sibelius** [comment]
# Frontend
- [ ] React - V - View - Responsável para renderização dos componentes
- https://facebook.github.io/react/docs/tutorial.html
- ler blogs do medium sobre react - https://medium.com/search?q=react
- https://github.com/petehunt/react-howto - guia passo a passo do que aprender no ecossistema React
- Seguir esses caras no Twitter - https://medium.com/@dan_abramov/my-react-list-862227952a8c#.4v6k5v7l2
- Styles in JS - https://speakerdeck.com/vjeux/react-css-in-js
- [ ] Redux - Gerencia o estado do aplicativo de maneira previsivel
-  Super recomendo - https://egghead.io/series/getting-started-with-redux
- http://redux.js.org/
- [ ] React  Native - JS para Mobile
- http://facebook.github.io/react-native/
- https://rnplay.org/ - playground
- exponent ide - https://exponentjs.com/
- deco ide - https://www.decosoftware.com/
- [ ] Relay (Avançado)
- Assistir o vídeo (https://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html)

### Mais
- http://freecodecamp.com/ - bom para aprender do mais básico ao mais complexo (FullStack)
- Colocar a mão na massa mesma, fazer pequenos apps para aplicar o que foi aprendido, não existe shortcut
- Procurar exemplos de código no Github, tentar corrigir bugs de repositórios públicos, trabalhar no código dos outros melhora sua habilidade de programação

# Dúvidas

Qualquer dúvida pode mandar aqui no gitter: https://gitter.im/henriquesosa/react-native-dojo
