### ISSUE TITLE
Aplicativo para doação de sangue

### ISSUE THREAD

**Issue by henriquesosa** [react-native-dojo/react-native-dojo#2]
@rturk
# Ideia

Aplicativo para doação de sangue
- Mostrar Hospitais e pontos de coleta locais
- Push notification quando estoque de sangue estiver baixo
- Share em redes sociais
- Find friends
- Server side statistics
- Podemos nos basear nesse app para a NBA

**Comment by sibeliusseraphini** [comment]
@henriquesosa vamos tentar deixar as ideias para a issue #1 pra facilitar, ou precisa uma ideia por issue?

**Comment by henriquesosa** [comment]
@sibeliusseraphini não fica mais facil para tratar cada ideia individualmente?

**Comment by mfpalladino** [comment]
+1

**Comment by henriquesosa** [comment]
+1

**Comment by lucasbento** [comment]
+1

Para doação de sangue eu conheço esse: https://play.google.com/store/apps/details?id=br.com.heroes.android

**Comment by sibelius** [comment]
O problema desse aplicativo é que ele vai ser usado poucas vezes ao longo.
Um homem só pode doar sangue 4 vezes ao ano e uma mulher 3 vezes ao ano.

Não se justifica a criação de um app somente para isso

Talvez um serviço que envia 4 mensagem (ou +) para cada pessoa por ano, como se fosse um lembrete, seria suficiente

**Comment by henriquesosa** [comment]
Acredito que um hotsite para gerar a newsletter, e um serviço para gerar relatórios sobre, entraria nessa sua abordagem @sibeliusseraphini. O que acha?

**Comment by sibelius** [comment]
nesse caso acredito que não precisamos de toda uma stack bleeding edge para isso

**Comment by maugravena** [comment]
+1

Gostei da ideia, seria legal tbm ter um cadastro de usuários doadores e cada vez que fizer uma doação isso contaria como uma forma de pontuação podendo assim ter algum tipo de beneficio para os usuários do aplicativo
