### ISSUE TITLE
Aplicativo para as Olimpíadas 2016 do Brasil

### ISSUE THREAD

**Issue by henriquesosa** [react-native-dojo/react-native-dojo#3]
@sibeliusseraphini
# Ideia

Aplicativo para as Olimpíadas 2016 do Brasil
- Mostrar Atletas por pais e suas habilidades
- Mostrar Histórico de Medalhas
- Mostar horário dos eventos
- Entre outras coisas
- Podemos nos basear nesse app para a NBA

**Comment by keuller** [comment]
Os dados para o app seriam providos por qual entidade ? Existem algum serviço REST ou XML que fornecem os dados dos atletas ?
Curti muito a idéia.

**Comment by sibelius** [comment]
Não fiz uma pesquisa em relação a isso

Se for o caso podemos desenvolver um web crawler simples também para extrair tais informações

**Comment by sibelius** [comment]
Achei esse app sobre as Olimpiadas do Rio 2016 - https://play.google.com/store/apps/details?id=com.ajay.internetcheckapp
