### ISSUE TITLE
Starter Code/Boilerplate for server

### ISSUE THREAD

**Issue by sibelius** [react-native-dojo/react-native-dojo#4]
We need a starter code/boilerplate for the server
- koa vs express?
- graphql
- relay

anything more?

**Comment by keuller** [comment]
Só acredito que temos que ir uma pouco mais devagar, pois temos gente que ainda estão iniciando. Se criarmos algo muito "bleeding edge" podemos assustar quem ainda não conhece muito. Eu gostaria de propor algo mais baby-step, para primeiramente equializar todo mundo e, assim também criar uma base de conhecimento legal. Pois temos que pensar, em atrair outras pessoas iniciantes também. Isso é o que fortalece a comunidade, podermos atingir a todos os níveis --- begginers - middle - advanced!

**Comment by sibelius** [comment]
Bem pensado, podemos ir construindo os boilerplate aos poucos com issues pequenas, para atender os requisitos da ideia escolhida

**Comment by lucasbento** [comment]
Claro que para beginners seria legal algo mais básico porém [SailsJS](sailsjs.org) também seria uma boa opção para um fast-prototype.
