### ISSUE TITLE
Starter Code/Boilerplate for web (react)

### ISSUE THREAD

**Issue by sibelius** [react-native-dojo/react-native-dojo#6]
- react
- react dom
- router
- css ? scss ? postcss?
- relay

**Comment by henriquesosa** [comment]
Criei uma primeira versão bem básica

**Comment by lucasbento** [comment]
Acho que Stylus seria uma boa opção pois podemos tanto utilizar a sintaxe dele quanto a sintaxe padrão do CSS (caso seja necessário).

**Comment by henriquesosa** [comment]
Estava pensando tambem em usar o post css

**Comment by sibelius** [comment]
@henriquesosa bom comentar aqui o link para o repositorio pra manter o track

**Comment by henriquesosa** [comment]
https://github.com/react-native-dojo/react-boilerplate
