### ISSUE TITLE
Aplicativo para documentação de Decisões

### ISSUE THREAD

**Issue by guipsamora** [react-native-dojo/react-native-dojo#9]
**# Ideia**

App para registros de decisões pessoais e de empresas, assim depois você poderia avaliar seu processo de decisão e se essas decisões, no final, foram boas ou não. 
Algumas features:
- Login individual
- Registro da decisão
- Inclusão de dados de cada decisão como: dia, quem(owner), motivo, plano de contingência(IF-THEN), expectativa
- Data futura para revisão da decisão - na data o card da decisão voltaria para a home do app e você poderia colocar mais algumas informações como: resultado, aprendizados, 👍 ou 👎

É uma ideia aberta para sugestões!! Abs

**Comment by sibelius** [comment]
@guipsamora bem interessante

Quais aplicativos provêem uma solução mais próxima disso?

**Comment by guipsamora** [comment]
@sibeliusseraphini dessa maneira não conheço nenhum, mas pode-se usar um Trello Board ou Asana, junto com um google docs. Mas não sei quão organizado ficaria. 

Em uma empresa com uns amigos, escrevíamos as decisões em um google docs direto, mas começaram a aparecer algumas dificuldades, como revisão e compartilhamento com novos membros
